Try github action.

diff --git a/.github/workflows/run-kathara-test.yml b/.github/workflows/run-kathara-test.yml
--- a/.github/workflows/run-kathara-test.yml
+++ b/.github/workflows/run-kathara-test.yml
@@ -26,6 +26,6 @@ jobs:
             echo "::set-output name=status::$?"
       - name: Check kathara lstart exit code
         if: ${{ steps.kathara-lstart.outputs.status != 0 }}
-          run: |
-            echo "::error title={Kathara lstart error}::{Cannot start the lab with the current configuration}"
-            exit 1
+        run: |
+          echo "::error title={Kathara lstart error}::{Cannot start the lab with the current configuration}"
+          exit 1
